### ISSUE TITLE
Emoji discord server isn't up

### ISSUE THREAD

**Issue by lol123123987** [Androz2091/AtlantaBot#451] opened 2021-04-28 15:23 UTC
**Please describe the problem you are having in as much detail as possible:**
https://www.atlanta-bot.fr/emojis is giving a 404 error and as such i can't add emoji functionality on my selfhosted atlanta

**To Reproduce**
Steps to reproduce the behavior: selfhost the bot, i guess

**Expected behavior**
A clear and concise description of what you expected to happen: invite link is up and running and i can join the server

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Further details:**
- atlanta version: n/a
- discord.js version: n/a
- Node.js version: n/a
- Operating system: windows

**Additional context**
Add any other context about the problem here: more than anything i just want an explanation to why the server isn't up anymore, or some external resource from which to get the emojis

**Comment by Androz2091** [comment] 2021-05-14 09:19
Duplicate of #457

**Closed by Androz2091** 2021-05-14 09:19 UTC
