### ISSUE TITLE
Support Server?

### ISSUE THREAD

**Issue by RyanChan020408** [Androz2091/AtlantaBot#453] opened 2021-04-29 10:13 UTC
Any support server?
I get an error in https://discord.atlanta-bot.fr/ 
Error:
Error 1016 
What happened?
You've requested a page on a website (discord.atlanta-bot.fr) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (discord.atlanta-bot.fr).

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. Additional troubleshooting information here.

**Comment by Androz2091** [comment] 2021-05-14 09:19
Duplicate of #457

**Closed by Androz2091** 2021-05-14 09:19 UTC
