### ISSUE TITLE
Ticket System

### ISSUE THREAD

**Issue by joeyk710** [Androz2091/AtlantaBot#372] opened 2021-01-06 06:31 UTC
**Is your feature request related to a problem? Please describe.**
I see that there is a reports command and a suggest command. I noticed in the code there was an option about tickets. Is there a ticket system? Please add that.
**Describe the solution you'd like**
Please add a ticket system.
**Describe alternatives you've considered**

**Additional context**

**Comment by Androz2091** [comment] 2021-01-24 14:37
duplicate of #337

**Closed by Androz2091** 2021-01-24 14:37 UTC
